name: Cypress CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          record: false
          command: run # roda os testes
          headed: false # modo headless
          group: "CI Tests"
          config: |
            video=true
            screenshotOnRunFailure=true
            videosFolder=cypress/videos
            screenshotsFolder=cypress/screenshots
            videoUploadOnPasses=true

      - name: Upload Cypress artifacts
        uses: actions/upload-artifact@v4 # atualizar para v4
        with:
          name: cypress-evidence
          path: |
            cypress/videos/**
            cypress/screenshots/**
