name: Cypress CI with Evidence

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          record: false
          headed: false
          command: run
          group: "CI Tests"
          config: |
            video=true
            screenshotOnRunFailure=true
            videosFolder=cypress/videos
            screenshotsFolder=cypress/screenshots
            videoUploadOnPasses=true

      - name: Rename Cypress artifacts with job/test name
        run: |
          # Criar pastas separadas
          mkdir -p cypress/evidence/videos cypress/evidence/screenshots
          # Renomear vídeos
          for f in cypress/videos/**/*.mp4; do
            if [ -f "$f" ]; then
              mv "$f" "cypress/evidence/videos/$(basename "$f" | tr ' ' '_')"
            fi
          done
          # Renomear screenshots
          for f in cypress/screenshots/**/*.{png,jpg}; do
            if [ -f "$f" ]; then
              mv "$f" "cypress/evidence/screenshots/$(basename "$f" | tr ' ' '_')"
            fi
          done

      - name: Upload Cypress artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cypress-evidence
          path: |
            cypress/evidence/videos/**
            cypress/evidence/screenshots/**
