name: Cypress CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # 1. Pegar o código do repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Instalar dependências do projeto
      - name: Install dependencies
        run: npm ci

      # 4. Rodar testes Cypress headless no Chrome
      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          record: false
          headed: false # headless
          command: run
          group: "CI Tests"
          config: |
            video=true
            screenshotOnRunFailure=true
            videosFolder=cypress/videos
            screenshotsFolder=cypress/screenshots
            videoUploadOnPasses=true

      # 5. Fazer upload das evidências (vídeos e screenshots)
      - name: Upload Cypress artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cypress-evidence
          path: |
            cypress/videos/**
            cypress/screenshots/**
